### ISSUE TITLE
Choosing a directory containing JSON files exported from Sketch creates a new Sketch file that cannot be opened

### ISSUE THREAD

**Issue by JaseMiller** [littlebusters/Sketch-Exchanger#3]
I've tried this many times since installing `Sketch-Exchanger` and it consistently fails. I have some JSON files generated from a Sketch file (originally named "flow-mobile-reviews") which I have somehow deleted. I wanted to recreate the Sketch file from the JSON files I once exported.

1. Here's what happens for me. Creating a new Sketch file ("Untitled") allows me to access the **Exchanger** plugin in the Plugins menu. 
2. A window appears prompting me to open an "unzipped" directory or a ".sketch" file. 
3. I select and open the directory with the JSON data and Exchanger tells me a new file was created and opened. 
4. Then I get a pop error in Sketch stating: "The document “flow-mobile-reviews.sketch” could not be opened."
5. A new Sketch file does, in fact, appear in the Finder alongside the directory with the JSON files in it and it's named correctly after those files. 

So, my guess is that Exchanger is working most of the way but something is causing the newly generated Sketch file to be unusable by Sketch. When I attempt to open the file from Finder I get the same error that says, "The document “flow-mobile-reviews.sketch” could not be opened."

Any thoughts/fixes?

**Comment by littlebusters** [comment]
Hi!
To restore the Sketch file, you need the same file as when unzipped.
You selected directory content was same (or similar) this screenshot?
![image](https://user-images.githubusercontent.com/1303440/34993798-d7ea664c-fb14-11e7-9004-2cf4e8d7002a.png)

**Comment by JaseMiller** [comment]
Thanks for responding. I figured out that it was missing the `document.json` file that should have been there. I'm not sure if it wasn't generated properly or if the file was somehow accidentally deleted. It also did not have `meta.json` or `user.json` files. Manually re-creating those files isn't really an option, right?

**Comment by JaseMiller** [comment]
I think I did this already, but I'll try the full process with a different file from scratch to see if this error persists or if it was isolated to that one particular file (which was missing `json` files it should have had)...

**Comment by JaseMiller** [comment]
Update: I created a new Sketch file to re-test Exchanger. When the Exchanger Open dialogue box appeared, stating ```Choose `.sketch` or unziped folder...``` I selected the new Sketch file I created and then clicked `Open`. I got a success message from Exchanger near the bottom of my file's screen saying the configuration files had been created. However, I can't find them anywhere. They're not in the folder with the Sketch file, nor in my list of recently modified files on my system. Am I missing something?

**Comment by littlebusters** [comment]
Thank you for reporting!
I'm sorry, there was a bug in the plugin. It dosen't  work properly if spaces are included in the file or directory name.
Please update and try again.
Thanks.

**Comment by JaseMiller** [comment]
You're right. Removing all spaces from the file name and directory it was in got it to work. Any plans to fix that bug? :) Thx!

**Comment by littlebusters** [comment]
It has already been fixed. Try it again!!
![寿司ゆき:04](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/04.png)

**Comment by JaseMiller** [comment]
Yes, thanks! It works now with spaces in files and folders. Great news. Cheers.
